### PR TITLE
Improve performance by excluding compiled soy files from babel

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
When looking into https://github.com/metal/metal-tools-soy/issues/22 I noticed this small improvement could be made. The compiled soy files are already CJS so babel doesn't need to process them a second time. It should shave a couple of seconds off the build time on larger projects like WeDeploy console.

**Comment by Robert-Frampton** [comment]
@eduardolundgren

**Comment by eduardolundgren** [comment]
LGTM. Do you have the numbers on how much this improved the console build time?

**Comment by Robert-Frampton** [comment]
Hey @eduardolundgren,

It's not a massive improvement, but helps a little bit.

```bash
buildClient: 7809.905ms
```

**Pull request merged**
